[package]
name = "xdg-desktop-file-override"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tempfile = "3.2"

[dev-dependencies]
tempfile = "3.2"
